version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - HOST=db
      - PORT=5432
      - USER=postgres
      - PASSWORD=admin
      - NAME=auth_service
      - JWT_SECRET=secret-key
      - SERVER_PORT=8081
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_service
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge