// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/auth-service/internal/services (interfaces: Notifier)

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendSecurityAlert mocks base method.
func (m *MockNotifier) SendSecurityAlert(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSecurityAlert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSecurityAlert indicates an expected call of SendSecurityAlert.
func (mr *MockNotifierMockRecorder) SendSecurityAlert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSecurityAlert", reflect.TypeOf((*MockNotifier)(nil).SendSecurityAlert), arg0, arg1)
}
